/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectveiculo.view;

import com.mycompany.projectveiculo.modelo.Carro;
import com.mycompany.projectveiculo.modelo.Moto;
import com.mycompany.projectveiculo.veiculoController.MotoController;
import com.mycompany.projectveiculo.veiculoController.carroController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.den
 */
public class mainWindow extends javax.swing.JFrame {
    MotoController motoController = new MotoController();
    carroController carControler = new carroController();
    
    
    private DefaultTableModel metodosDaTabelaCarro;
    private DefaultTableModel metodosDaTabelaMoto;
    
    /**
     * Creates new form mainWindow
     */
    
    // Enviar dados da linha selecionada da tabela para os campos
    public mainWindow() {
        initComponents();
        
        metodosDaTabelaCarro = (DefaultTableModel) tabelaDeCarro.getModel();
        metodosDaTabelaMoto = (DefaultTableModel) tabelaDeMoto.getModel();
        
        tabelaDeCarro.getSelectionModel().addListSelectionListener(e ->{
            int linhaSelecionada = tabelaDeCarro.getSelectedRow();
            
            if (linhaSelecionada != -1){
                String marcaDoCarro = tabelaDeCarro.getValueAt(linhaSelecionada, 0).toString();
                String modeloDoCarro = tabelaDeCarro.getValueAt(linhaSelecionada, 1).toString();
                String qtdDePortasDoCarro = tabelaDeCarro.getValueAt(linhaSelecionada, 2).toString();
                
                modeloDoVeiculo.setText(modeloDoCarro);
                marcaDoVeiculo.setText(marcaDoCarro);
                campoQtdPortasDoCarro.setText(qtdDePortasDoCarro);
            }
        });
        
        tabelaDeMoto.getSelectionModel().addListSelectionListener(e -> {
            int linhaSelecionada = tabelaDeMoto.getSelectedRow();
            
            if (linhaSelecionada != -1){
                String marcaDaMoto = tabelaDeMoto.getValueAt(linhaSelecionada, 0).toString();
                String modeloDaMoto = tabelaDeMoto.getValueAt(linhaSelecionada, 1).toString();
                String valorDaCilindrada = tabelaDeMoto.getValueAt(linhaSelecionada, 2).toString();
                
                marcaDoVeiculo.setText(marcaDaMoto);
                modeloDoVeiculo.setText(modeloDaMoto);
                campoCilindradasDaMoto.setText(valorDaCilindrada);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marcaDoVeiculo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        modeloDoVeiculo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tipoDeVeiculoBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoCilindradasDaMoto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        botaoAlterarDados = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoLimparCampo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDeMoto = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDeCarro = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        campoQtdPortasDoCarro = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("registro automotivo");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Car Register");

        jLabel3.setText("sistema de registro veicular");

        jLabel4.setText("by carBrasilian");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel11)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );

        jLabel5.setText("Modelo *");

        marcaDoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaDoVeiculoActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca *");

        jLabel7.setText("Tipo de veículo *");

        tipoDeVeiculoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));

        jLabel8.setText("Cilindradas (p/moto)");

        jLabel9.setText("Quantidade de portas(p/carro)");

        jLabel10.setText("Carros");

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoAlterarDados.setText("Alterar");
        botaoAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarDadosActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoLimparCampo.setText("Limpar");
        botaoLimparCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCampoActionPerformed(evt);
            }
        });

        tabelaDeMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cilindradas"
            }
        ));
        tabelaDeMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDeMotoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDeMoto);

        tabelaDeCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Nº Portas"
            }
        ));
        jScrollPane3.setViewportView(tabelaDeCarro);

        jLabel12.setText("Motos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(tipoDeVeiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(marcaDoVeiculo)
                                    .addComponent(jLabel6)
                                    .addComponent(modeloDoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(botaoCadastrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoLimparCampo)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(campoCilindradasDaMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(botaoAlterarDados)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaoRemover))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(campoQtdPortasDoCarro))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(199, 199, 199)
                                .addComponent(jLabel12)))
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoDeVeiculoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCilindradasDaMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcaDoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoQtdPortasDoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloDoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAlterarDados)
                    .addComponent(botaoRemover))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoLimparCampo))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void marcaDoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaDoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaDoVeiculoActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
        String veiculo = tipoDeVeiculoBox.getSelectedItem().toString();
        String marca = marcaDoVeiculo.getText().toLowerCase();
        String modelo = modeloDoVeiculo.getText().toLowerCase();
        String qtdDePortas = campoQtdPortasDoCarro.getText();
        String cilindradas = campoCilindradasDaMoto.getText();
        
        if (veiculo.equals("Moto")){
            if (marca.isEmpty() || modelo.isEmpty() || cilindradas.isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos ou altere o tipo de veículo"
                    , "Atenção!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                int cilindradasDaMoto = Integer.parseInt(cilindradas.trim());

                if (cilindradasDaMoto > 2000){
                    JOptionPane.showMessageDialog(null, "Valor de cilindrada inválida", "Atenção",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            
                metodosDaTabelaMoto.setRowCount(0);
                ArrayList<Moto> listaDeMotos = motoController.listarMotosCadastradas();
                if (veiculo.equals("Moto")){
                    motoController.dataBaseControllerMotoAdicionar(marca, modelo, cilindradasDaMoto);
                    for (Moto moto : listaDeMotos){
                        metodosDaTabelaMoto.addRow(new Object[]{moto.getMarca(), moto.getModelo(), moto.getCilindradas()});
                    }
                    marcaDoVeiculo.setText("");
                    modeloDoVeiculo.setText("");
                    campoCilindradasDaMoto.setText("");
                }
            
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Digite um número válido!", "Atenção!",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else if (veiculo.equals("Carro")){
            
            if (marca.isEmpty() || modelo.isEmpty() || qtdDePortas.isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos ou altere o tipo de veículo", 
                        "Atenção!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            try {
                int qtdPortasDoCarro = Integer.parseInt(qtdDePortas.trim());
            
                if (qtdPortasDoCarro > 4 || qtdPortasDoCarro < 2){
                    JOptionPane.showMessageDialog(null, "Digite um número de portas entre 2 e 4", "Atenção!",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            
                metodosDaTabelaCarro.setRowCount(0);
                ArrayList<Carro> listaDeCarros = carControler.listarCarrosCadastrados();
                if (veiculo.equals("Carro")){
                    carControler.dataBaseControllerCarroAdicionar(marca, modelo, qtdPortasDoCarro);
                    for (Carro carro : listaDeCarros){
                        metodosDaTabelaCarro.addRow(new Object[] {carro.getMarca(), carro.getModelo(), carro.getQtdPortas()});
                    }
                
                    marcaDoVeiculo.setText("");
                    modeloDoVeiculo.setText("");
                    campoQtdPortasDoCarro.setText("");
                }
            
            
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Digite um número válido!", "Atenção",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Tipo de veículo inválido!", "Atenção!",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarDadosActionPerformed
        // TODO add your handling code here:
        String tipoVeiculo = tipoDeVeiculoBox.getSelectedItem().toString();
        int linhaSelecionadaTblCarro = tabelaDeCarro.getSelectedRow();
        int linhaSelecionadaTblMoto = tabelaDeMoto.getSelectedRow();
        
        if (linhaSelecionadaTblCarro == -1 && linhaSelecionadaTblMoto == -1){
            JOptionPane.showMessageDialog(null, "Selecione um veículo para alterar.", "Atenção!",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (linhaSelecionadaTblCarro != -1 && linhaSelecionadaTblMoto != -1){
            JOptionPane.showMessageDialog(null, "Selecione a linha de somente uma tabela!",
                    "Atenção!", JOptionPane.ERROR_MESSAGE);
            atualizarTabelaCarro();
            atualizarTabelaMoto();
            return;
        }
        
        if (tipoVeiculo.equals("Carro")){
            if (linhaSelecionadaTblCarro != -1){
                metodosDaTabelaCarro.setValueAt(marcaDoVeiculo.getText(), linhaSelecionadaTblCarro, 0);
                metodosDaTabelaCarro.setValueAt(modeloDoVeiculo.getText(), linhaSelecionadaTblCarro , 1);
                metodosDaTabelaCarro.setValueAt(campoQtdPortasDoCarro.getText(), linhaSelecionadaTblCarro, 2);
                JOptionPane.showMessageDialog(null, "Atualização concluída com sucesso!", 
                    "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                    return;
            }else{
                JOptionPane.showMessageDialog(null, "Altere o tipo de veículo!",
                        "Atenção!", JOptionPane.ERROR_MESSAGE);
                    return;
            }
        }else if (tipoVeiculo.equals("Moto")){
            if (linhaSelecionadaTblMoto != -1){
                metodosDaTabelaMoto.setValueAt(marcaDoVeiculo.getText(), linhaSelecionadaTblMoto, 0);
                metodosDaTabelaMoto.setValueAt(modeloDoVeiculo.getText(), linhaSelecionadaTblMoto, 1);
                metodosDaTabelaMoto.setValueAt(campoCilindradasDaMoto.getText(), linhaSelecionadaTblMoto, 2);
                JOptionPane.showMessageDialog(null, "Atualização concluída com sucesso!", 
                    "Atenção!", JOptionPane.INFORMATION_MESSAGE);
                    return;
            }else{
                JOptionPane.showMessageDialog(null, "Altere o tipo de veículo!",
                        "Atenção!", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_botaoAlterarDadosActionPerformed

    private void botaoLimparCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCampoActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_botaoLimparCampoActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        // TODO add your handling code here:
        int linhaSelecionadaTbCarro = tabelaDeCarro.getSelectedRow();
        int linhaSelecionadaTblMoto = tabelaDeMoto.getSelectedRow();
        
        if (linhaSelecionadaTbCarro == -1 && linhaSelecionadaTblMoto == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma das linhas da tabela para remover",
                    "Atenção", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (linhaSelecionadaTbCarro != -1){
            ArrayList<Carro> listaDeCarros = carControler.listarCarrosCadastrados();
            listaDeCarros.remove(linhaSelecionadaTbCarro);
            atualizarTabelaCarro();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Linha removida com sucesso!", "Atenção!",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        if (linhaSelecionadaTblMoto != -1){
            ArrayList<Moto> listaDeMotos = motoController.listarMotosCadastradas();
            listaDeMotos.remove(linhaSelecionadaTblMoto);
            atualizarTabelaMoto();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Linha removida com sucesso!", "Atenção!",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void tabelaDeMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDeMotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDeMotoMouseClicked
    
    private void atualizarTabelaCarro() {
        metodosDaTabelaCarro.setRowCount(0);
        for (Carro carro : carControler.listarCarrosCadastrados()){
            metodosDaTabelaCarro.addRow(new Object[] {carro.getMarca(), 
                carro.getModelo(), carro.getQtdPortas()});
        }
    }
    
    private void atualizarTabelaMoto() {
        metodosDaTabelaMoto.setRowCount(0);
        for (Moto moto : motoController.listarMotosCadastradas()){
            metodosDaTabelaMoto.addRow(new Object[] {moto.getMarca(),
            moto.getModelo(), moto.getCilindradas()});
        }
    }
    
    private void limparCampos(){
        marcaDoVeiculo.setText("");
        modeloDoVeiculo.setText("");
        campoCilindradasDaMoto.setText("");
        campoQtdPortasDoCarro.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarDados;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLimparCampo;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JTextField campoCilindradasDaMoto;
    private javax.swing.JTextField campoQtdPortasDoCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField marcaDoVeiculo;
    private javax.swing.JTextField modeloDoVeiculo;
    private javax.swing.JTable tabelaDeCarro;
    private javax.swing.JTable tabelaDeMoto;
    private javax.swing.JComboBox<String> tipoDeVeiculoBox;
    // End of variables declaration//GEN-END:variables
}
