/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_de_estoque.View;

import com.mycompany.sistema_de_estoque.Controle.UsuarioControle;
import javax.swing.JOptionPane;

/**
 *
 * @author Ericsson Dos Santos
 */
public class JanelaDeRegistro extends javax.swing.JFrame {
    UsuarioControle userControle = new UsuarioControle();
    /**
     * Creates new form JanelaDeRegistro
     */
    public JanelaDeRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoDeNovoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDeNovaSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        campoConfirmacaoDeSenha = new javax.swing.JPasswordField();
        botaoRegistrarNovoUsuario = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setText("Crie um nome de usuário");

        jLabel4.setText("Crie uma senha");

        jLabel5.setText("Confirme sua senha");

        botaoRegistrarNovoUsuario.setText("REGISTRAR");
        botaoRegistrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRegistrarNovoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(campoDeNovaSenha)
                            .addComponent(campoConfirmacaoDeSenha)
                            .addComponent(campoDeNovoUsuario)
                            .addComponent(botaoRegistrarNovoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDeNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDeNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoConfirmacaoDeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botaoRegistrarNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRegistrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRegistrarNovoUsuarioActionPerformed
        // TODO add your handling code here:
        String dadoDeRegistroLogin = campoDeNovoUsuario.getText();
        String dadoDeRegistroSenha = new String(campoDeNovaSenha.getPassword());
        String confirmacaoDeSenha = new String(campoConfirmacaoDeSenha.getPassword());
        
        if (dadoDeRegistroLogin == null || dadoDeRegistroSenha == null || 
                confirmacaoDeSenha == null || dadoDeRegistroLogin.isEmpty() || 
                dadoDeRegistroSenha.isEmpty() || confirmacaoDeSenha.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Atenção!",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        boolean retornoDaCentral = userControle.registrarUsuarioNaCentral(dadoDeRegistroLogin, dadoDeRegistroSenha, confirmacaoDeSenha);
        
        if (!retornoDaCentral) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar cadastro, tente novamente ou entre em contato com o suporte!", 
                    "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Registro realizado com sucesso!", "Sucesso!",
                JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_botaoRegistrarNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaDeRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaDeRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRegistrarNovoUsuario;
    private javax.swing.JPasswordField campoConfirmacaoDeSenha;
    private javax.swing.JPasswordField campoDeNovaSenha;
    private javax.swing.JTextField campoDeNovoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
